version: '2'

services:
  autotrader-graphql-api:
    build: ./autotrader_graphql_api
    environment:
      - RESIDENTIAL_PROXY=http://${RESIDENTIAL_PROXY_USERNAME}:${RESIDENTIAL_PROXY_PASSWORD}@gate.smartproxy.com:${RESIDENTIAL_PROXY_PORT}
      - FLASK_AUTH_TOKEN=${FLASK_AUTH_TOKEN}

    ports:
      - "5000:5000"
  
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "5001:6379"
  
  pulsar:
    build: ./pulsar
    volumes:
      - ./pulsar/pulsardata:/pulsar/data
    
    command: "bin/pulsar standalone"

    ports:
      - 5002:6650
      - 5003:8080


