version: '2'

services:
  rest-api:
    build: ./restApi
    environment:
      - RESIDENTIAL_PROXY=http://${RESIDENTIAL_PROXY_USERNAME}:${RESIDENTIAL_PROXY_PASSWORD}@gate.smartproxy.com:${RESIDENTIAL_PROXY_PORT}
      - FLASK_AUTH_TOKEN=${FLASK_AUTH_TOKEN}

    ports:
      - ${REST_API_PORT}:5000
  
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - ${REDIS_PORT}:6379
  
  pulsar:
    build: ./pulsar
    volumes:
      - ./pulsar/pulsardata:/pulsar/data
    
    command: "bin/pulsar standalone"

    ports:
      - ${PULSAR_PORT_1}:6650
      - ${PULSAR_PORT_2}:8080
  
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    ports:
      - ${MONGO_INITDB_PORT}:27017
    volumes:
      - ./mongodb/database:/data/db
  
  listing-spider:
    build:
      context: ./autoTrader/
      dockerfile: Dockerfile.listing
    environment:
      - RESIDENTIAL_PROXY=http://${RESIDENTIAL_PROXY_USERNAME}:${RESIDENTIAL_PROXY_PASSWORD}@gate.smartproxy.com:${RESIDENTIAL_PROXY_PORT}
    
    depends_on:
      - pulsar
      - redis
  
  transform:
    build:
      context: ./transform
      dockerfile: Dockerfile
  